version: "3.8"
services:
    app:
        build: .
        container_name: php-tasks
        working_dir: /var/www/
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./php.ini:/usr/local/etc/php/conf.d/php.ini
        networks:
            - app-network

    db:
        image: mariadb
        container_name: db-tasks
        restart: unless-stopped
        ports:
            - "3306:3306"
        tty: true
        environment:
            MYSQL_ROOT_PASSWORD: 1234
            MYSQL_DATABASE: db_c2p
            MYSQL_USER: admin
            MYSQL_PASSWORD: 1234
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - dbdata:/var/lib/mysql/
            - ./my.cnf:/etc/mysql/my.cnf
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
